monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        markdown_logging:
            type: stream
            path: "%kernel.logs_dir%/markdown.log"
            level: debug
            channels: ["markdown"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
